config/routes.rb
Rails.application.routes.draw do

    root 'links#index'

    # Rename devise routes, and define custom controller
    devise_for :users,
        path: 'user',
        controllers: {
            registrations: 'registrations'
        },
        path_names: {
            sign_in: 'login',
            sign_out: 'logout',
            sign_up: 'register'
        }

    # Extend user routes
    resources :users,
        path: 'user',
        only: [:index, :show]

    get '~:id', to: 'users#show'

    resources :links do
        resources :comments
    end

end

app/models/comment.rb
class Comment < ActiveRecord::Base

    belongs_to :link
    belongs_to :user
    validates :body, presence: true

end

app/models/link.rb
require 'uri'

class Link < ActiveRecord::Base

    has_many :comments, dependent: :destroy
    belongs_to :user
    validates :title, :url,
        presence: true

    def validate
        begin
            uri = URI.parse(url)
            rescue URI::InvalidURIError
                errors.add(:url, 'The format of the url is not valid.')
        end
    end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username,
    presence: true,
    length: { in: 1..64 }

  has_many :comments, dependent: :destroy
  has_many :links, dependent: :destroy

  def to_param
    username
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    before_action :authenticate_user!

    def create
        @link = get_link
        @comment = @link.comments.new comment_params
        @comment.user_id = current_user.id

        if @comment.save
            redirect_to @link
        else
            render 'form'
        end
    end

    def destroy
        @comment = get_comment

        if @comment.user === current_user
            @comment.destroy
        end

        redirect_to @comment.link
    end

    private

        def get_link
            Link.find params[:link_id]
        end

        def get_comment
            link = get_link
            link.comments.find params[:id]
        end

        def comment_params
            params.require(:comment).permit(:body)
        end

end

app/controllers/links_controller.rb
require 'open-uri'

class LinksController < ApplicationController

    before_action :authenticate_user!,
        except: [:index, :show]

    def index
        @links = view_context.latest Link.all

        if user_signed_in?
            @link = current_user.links.new
        end
    end

    def show
        @link = Link.find params[:id]

        # Extract article from webpage
        @link_content = extract_content @link.url
    end

    def new
        @link = current_user.links.new
    end

    def edit
        @link = current_user.links.new
    end

    def create
        @link = current_user.links.new link_params

        if @link.save
            redirect_to @link
        end
    end

    def update
        @link = Link.find params[:id]

        if @link.user === current_user
            @link.update link_params
        end

        redirect_to @link
    end

    def destroy
        @link = Link.find params[:id]

        if @link.user === current_user
            @link.destroy
        end

        redirect_to links_path
    end

    private

        def link_params
            params.require(:link)
                .permit(:title, :url)
        end

        def extract_content(url)
            html = open(url).read
            extracted = Readability::Document.new html,
                tags: %w(div a p h1 h2 h3 h4 h5 h6 hr img pre code ul li ol blockquote em strong),
                attributes: %w(src href id),
                remove_empty_nodes: false

            extracted.content
        end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private

        def sign_up_params
            params.require(:user)
                .permit(:username, :email, :password, :password_confirmation)
        end

        def account_update_params
            params.require(:user)
                .permit(:username, :email, :password, :password_confirmation, :current_password)
        end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
        @users = User.all
    end

    def show
        username = params[:id]
        @user = User.find_by username: username

        if !@user
            @error_msg = "Sorry, there is no user called ~#{username}"
            render 'shared/404'
        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

    def latest(query, limit=25)
        query.order(created_at: :desc)
            .limit(limit)
    end

    def page_header(title, subtitle=nil)
        content_for :title, title
        small = subtitle ? " <small>#{subtitle}</small>" : ""

        "<div class='page-header'><h1>#{title + small}</h1></div>"
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
require 'uri'

module LinksHelper

    def prettify_url(url)
        URI.parse(url).host
            .sub('www.', '')
    end

end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper

    def format_username(user)
        link_to '~' + user.username, user_path(user)
    end

end

app/views/comments/_comment.html.erb
<div class="list-group-item">

    <% @comment = comment %>
    <%= format_username(@comment.user) %>

    <section><%= @comment.body %></section>

    <%= render 'comments/metadata' %>

</div>

app/views/comments/_form.html.erb
<% if user_signed_in? %>

    <%= form_for [@link, @link.comments.build] do |f| %>

        <p>
            <%= f.label :body %><br />
            <%= f.text_area :body %>
        </p>

        <p>
            <%= f.submit %>
        </p>

    <% end %>

<% else %>

    <span>You must <%= link_to 'log in', new_user_session_path %> or
    <%= link_to 'sign up', new_user_registration_path %> to comment on posts.</span>

<% end %>

app/views/comments/_metadata.html.erb
<ul class="metadata comment-metadata">
    <li class="time posted" title="<%= @comment.created_at %>">
        <%= time_ago_in_words(@comment.created_at) %> ago
    </li>

    <% if @comment.updated_at != @comment.created_at %>
        <li class="time updated" title="<%= @comment.updated_at %>">
            updated <%= time_ago_in_words(@comment.updated_at) %> ago
        </li>
    <% end %>

    <% if @comment.user.username === current_user.username %>
        <li class='delete'>
            <%= link_to 'delete', [@comment.link, @comment],
                method: :delete,
                data: { confirm: 'Are you sure?' }
             %>
         </li>
    <% end %>
</ul>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">

        <div class="navbar-header">

            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <%= link_to 'Linkshare', root_path, class: 'navbar-brand' %>
        </div>

        <div id="navbar" class="navbar-collapse collapse">

            <ul class="nav navbar-nav">
                <li><%= link_to 'Recent links', links_path %></li>
                <li><%= link_to 'Users', users_path %></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <%= render 'layouts/user_options' %>
            </ul>

        </div>

    </div>
</nav>

app/views/layouts/_notices.html.erb
    <section class="notices">
        <div class="notice"><%= notice %></div>
        <div class="alert"><%= alert %></div>
    </section>

app/views/layouts/_user_options.html.erb
<% if user_signed_in? %>
    <li><%= format_username(current_user) %></li>
    <li><%= link_to 'Account', edit_user_registration_path(current_user) %></li>
    <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
<% else %>
    <li><%= link_to 'Login', new_user_session_path %></li>
    <li><%= link_to 'Register', new_user_registration_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title><%= yield :title %> / Linkshare</title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>
<body>

    <%= render 'layouts/navbar' %>

    <div class="container">

        <%= render 'layouts/notices' %>

        <%= yield %>

    </div>

</body>
</html>

app/views/links/_form.html.erb
<% if user_signed_in? %>

    <%= form_for @link do |f| %>

        <p>
            <%= f.label :url %>
            <%= f.text_field :url, autofocus: true %>
        </p>

        <p>
            <%= f.label :title %>
            <%= f.text_field :title %>
        </p>

        <p>
            <%= f.submit %>
        </p>

    <% end %>

<% else %>

    <span><%= link_to 'Log in', new_user_session_path %> or
    <%= link_to 'sign up', new_user_registration_path %> to post links.</span>

<% end %>

app/views/links/_link.html.erb
<div class="list-group-item">

    <strong><%= link.title %></strong>
    <%= link_to prettify_url(link.url), link.url, class: :url %>

    <%= link_to pluralize(link.comments.length, 'comment'),
        link_path(link) + '#comments',
        class: 'badge'
    %>

    <%= render partial: 'links/metadata', locals: { link: link } %>

</div>

app/views/links/_metadata.html.erb
<ul class="metadata link-metadata">
    <li class="time posted" title="<%= link.created_at %>">
        posted by <%= link_to link.user.username, link.user %> <span class="time posted"><%= time_ago_in_words(link.created_at) %> ago</span>
    </li>

    <% if not link.comments.empty? %>
        <li class="time last-comment" title="<%= link.updated_at %>">
            last comment <%= time_ago_in_words(link.comments.last.updated_at) %> ago
        </li>
    <% end %>

    <% if link.user === current_user %>
        <li>
            <%= link_to 'delete', link,
                method: :delete,
                data: {
                    confirm: "Are you sure you want to delete '#{link.title}'?"
                },
                class: :delete
             %>
        </li>
    <% end %>
</ul>

app/views/links/index.html.erb
<% content_for :title, 'Home' %>

<div class="page-header">
    <h1>
        Linkshare
        <small>a reddit clone thing</small>
    </h1>
</div>

<section class="new-link">
    <h3>Post a new link</h3>
    <%= render 'form' %>
</section>

<% if @links.length > 0 %>
    <%= render @links %>
<% else %>
    There are no links yet. <%= link_to 'Post one.', new_link_path %>
<% end %>

app/views/links/new.html.erb
<% content_for :title, 'Post a new link' %>

<div class="page-header">
    <h1>Post a new link</h1>
</div>

<%= render 'form' %>

app/views/links/show.html.erb
<article>
    <%= page_header(@link.title, link_to(prettify_url(@link.url), @link.url)).html_safe %>

    <section class="content">
        <%= @link_content.html_safe %>
    </section>

    <h3>
        <a name="comments" class="anchor"></a>
        <%= pluralize @link.comments.length, 'Comment' %>
    </h3>

    <%= render @link.comments %>

    <h3>Add a comment</h3>
    <%= render 'comments/form' %>
</article>

app/views/shared/404.html.erb
<h1><%= @error_msg || 'Sorry, that page doesn\'t exist' %></h1>
<%= link_to 'Go home', root_path %>

app/views/users/_user.html.erb
<div class="list-group-item">
    <strong><%= format_username(user) %></strong>
    <ul class="metadata">
        <li>
            <%= link_to pluralize(user.links.length, 'link'), user_path(user) + '#links' %>
        </li>
        <li>
            <%= link_to pluralize(user.comments.length, 'comment'), user_path(user) + '#comments' %>
        </li>
    </ul>
</div>

app/views/users/index.html.erb
<%= page_header("Users").html_safe %>

<div class="list-group">
    <%= render @users %>
</div>

app/views/users/show.html.erb
<div class="page-header">
    <h1>
        <%= format_username(@user) %>
        <small>User for <%= time_ago_in_words(@user.created_at) %></small>
    </h1>
</div>

<h3>
    <a name="links" class="anchor"></a>
    Recent links
</h3>
<div class="list-group">
    <%= render latest @user.links, 10 %>
</div>

<h3>
    <a name="comments" class="anchor"></a>
    Recent comments
</h3>
<div class="list-group">
    <%= render latest @user.comments, 10 %>
</div>